-- Day 4: SQL JOINs

-- Q1. Show customer ID, customer name and order amount
-- for every order.

SELECT customers.customer_id, name, amount
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id;


-- Q2. Show customer name and order amount
-- for orders above 1000.

SELECT name, amount
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
WHERE amount > 1000;


-- Q3. Show all orders with customer names,
-- sorted from highest amount to lowest.

SELECT customers.customer_id, name, amount
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
ORDER BY amount DESC;


-- Q4. Show orders above 500 with customer names,
-- sorted from highest amount to lowest.

SELECT name, amount
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
WHERE amount > 500
ORDER BY amount DESC;


-- Q5. Show all orders placed by Amrit.

SELECT name, order_id, amount, email
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
WHERE name = 'amrit'
ORDER BY amount DESC;


-- Q6. Find the total amount spent by each customer
-- and show the customer's name.

SELECT customers.customer_id, name, SUM(amount) AS total
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, name;


-- Q7. Find customers whose total spending
-- is greater than 1000.

SELECT customers.customer_id, name, SUM(amount) AS total
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, name
HAVING SUM(amount) > 1000
ORDER BY total DESC;


-- Q8. Show each customer's name
-- and the number of orders they placed.

SELECT name, COUNT(order_id) AS order_count
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, name;


-- Q9. Show customers who placed at least 2 orders.

SELECT name, COUNT(order_id) AS order_count
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, name
HAVING COUNT(order_id) >= 2;


-- Q10. Create a restaurants table.

CREATE TABLE restaurants (
    restaurant_id INT PRIMARY KEY,
    restaurant_name VARCHAR(100),
    city VARCHAR(50)
);


-- Insert restaurants.

INSERT INTO restaurants (restaurant_id, restaurant_name, city)
VALUES
(1, 'Food Palace', 'Rourkela'),
(2, 'Spice Hub', 'Delhi'),
(3, 'Tasty Bites', 'Mumbai');


-- Add restaurant_id to orders.

ALTER TABLE orders
ADD restaurant_id INT;


-- Assign restaurants to orders.

UPDATE orders
SET restaurant_id = 1
WHERE order_id IN (101, 103, 105);

UPDATE orders
SET restaurant_id = 2
WHERE order_id IN (102, 104, 107);

UPDATE orders
SET restaurant_id = 3
WHERE order_id IN (106, 108);


-- Q11. Show customer name, restaurant name
-- and order amount for every order.

SELECT
    customers.name,
    restaurants.restaurant_name,
    orders.amount
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id;


-- Q12. Find total revenue generated by each restaurant.

SELECT
    restaurants.restaurant_name,
    restaurants.city,
    SUM(orders.amount) AS total_revenue
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_id,
         restaurants.restaurant_name,
         restaurants.city
ORDER BY total_revenue DESC;